"""
CLI-compatible agentic skill runner.

Loads a SKILL.md as the system prompt, runs the standard tool-calling loop,
and routes tool calls directly to Python functions — no MCP subprocess required.

Supports Claude (Anthropic SDK) and Gemini (REST API).
"""
from __future__ import annotations

import json
import os
import sys
from pathlib import Path
from typing import Any

import time

import anthropic
import requests
from dotenv import load_dotenv
from loguru import logger

_ROOT = Path(__file__).resolve().parent.parent
load_dotenv(_ROOT / ".env")

sys.path.insert(0, str(_ROOT))


def _resolve(file_path: str) -> str:
    """Resolve relative or root-relative paths against the project root.

    Handles three cases:
    - Fully-qualified absolute path (C:\\... on Windows, /... on Linux) → pass through
    - Root-relative with leading slash (/data/structures/x.cif, generated by the model
      when it assumes Linux) → strip slash, join with _ROOT
    - Plain relative path (data/structures/x.cif) → join with _ROOT

    The leading-slash strip is critical on Windows: pathlib's / operator interprets
    a slash-prefixed path as drive-relative, producing C:\\data\\... instead of
    _ROOT\\data\\...
    """
    p = Path(file_path)
    # Truly absolute: has a drive letter on Windows, or is_absolute() on Linux/Mac
    if p.is_absolute() and (sys.platform != "win32" or bool(p.drive)):
        return str(p)
    return str(_ROOT / Path(file_path.lstrip("/\\")))


# ---------------------------------------------------------------------------
# AA normalisation (mirrors structure_tools_server.py)
# ---------------------------------------------------------------------------

_ONE_TO_THREE: dict[str, str] = {
    "A": "ALA", "R": "ARG", "N": "ASN", "D": "ASP", "C": "CYS",
    "Q": "GLN", "E": "GLU", "G": "GLY", "H": "HIS", "I": "ILE",
    "L": "LEU", "K": "LYS", "M": "MET", "F": "PHE", "P": "PRO",
    "S": "SER", "T": "THR", "W": "TRP", "Y": "TYR", "V": "VAL",
}


# ---------------------------------------------------------------------------
# Tool definitions — one source of truth, converted per-provider
# ---------------------------------------------------------------------------

_TOOL_DEFS: list[dict[str, Any]] = [
    {
        "name": "search_corpus",
        "description": (
            "Semantically search the curated scientific literature corpus. "
            "Returns top-k paper fingerprints ranked by similarity, each with "
            "situational context, key quantitative findings (Kd, Ki), protein "
            "lists, DOI, study type, and study category. Use for proteins, "
            "mechanisms, assay results, inhibitors, or binding affinities."
        ),
        "parameters": {
            "type": "object",
            "properties": {
                "query": {
                    "type": "string",
                    "description": (
                        "Natural language query. Include protein names, mechanisms, "
                        "assay types, or quantitative terms for best results."
                    ),
                },
                "top_k": {
                    "type": "integer",
                    "description": "Number of results to return (1-20). Default 5.",
                },
                "study_type": {
                    "type": "string",
                    "description": "Optional methodology filter.",
                    "enum": [
                        "experimental_in_vitro", "experimental_in_vivo",
                        "experimental_structural", "computational", "review", "case_study",
                    ],
                },
                "study_category": {
                    "type": "string",
                    "description": (
                        "Optional domain filter. 'pathway_biology' for disease mechanism "
                        "papers; 'biochemistry' for binding assay papers."
                    ),
                    "enum": [
                        "biochemistry", "pathway_biology", "structural_biology",
                        "host_pathogen", "clinical", "review",
                    ],
                },
            },
            "required": ["query"],
        },
    },
    {
        "name": "get_fingerprint",
        "description": (
            "Retrieve the complete fingerprint for a specific paper by DOI or paper_key. "
            "Returns all key findings, methodology, contradictions, and entity lists. "
            "Use after search_corpus identifies a paper of interest."
        ),
        "parameters": {
            "type": "object",
            "properties": {
                "identifier": {
                    "type": "string",
                    "description": (
                        "DOI (e.g. '10.1021/jacs.5c12876') or paper_key "
                        "(e.g. 'doi:10.1021/jacs.5c12876'). Both forms accepted."
                    ),
                },
            },
            "required": ["identifier"],
        },
    },
    {
        "name": "find_pdb_structures",
        "description": (
            "Search the entire corpus fingerprint database for PDB structure accessions "
            "linked to specific proteins. Checks two sources across ALL fingerprints: "
            "(1) pathway_context.target_nodes.suggested_pdb_structures — PDB IDs curators "
            "associated with a target protein in pathway biology papers; "
            "(2) paper_metadata.pdb_accessions — PDB IDs mentioned in any paper where "
            "the protein appears in key findings or entity lists. "
            "Call once with all candidate target proteins before writing the PIPELINE HANDOFF. "
            "Use returned IDs verbatim — they are corpus-sourced, never hallucinated."
        ),
        "parameters": {
            "type": "object",
            "properties": {
                "proteins": {
                    "type": "array",
                    "items": {"type": "string"},
                    "description": (
                        "Gene symbols of proteins to look up, e.g. ['YAP1', 'TEAD4', 'NF2']. "
                        "Include all proteins from all candidate PPIs in one call."
                    ),
                },
            },
            "required": ["proteins"],
        },
    },
    {
        "name": "search_rcsb_pdb",
        "description": (
            "Search RCSB PDB for structures containing specific proteins. "
            "Use as a fallback ONLY when find_pdb_structures returns total_found=0 "
            "(corpus has no PDB IDs for your target proteins). "
            "Performs a full-text search on RCSB and returns up to 5 entries per protein "
            "with title, method, resolution, chain count, and entity descriptions. "
            "Results are NOT corpus-sourced — check entity descriptions to confirm "
            "the complex you want is actually present before using a PDB ID."
        ),
        "parameters": {
            "type": "object",
            "properties": {
                "proteins": {
                    "type": "array",
                    "items": {"type": "string"},
                    "description": (
                        "Gene symbols of proteins to search for, e.g. ['YAP1', 'TEAD4']. "
                        "Focus on the primary target proteins — 2–3 gene symbols is sufficient."
                    ),
                },
            },
            "required": ["proteins"],
        },
    },
    {
        "name": "tool_analyze_interface",
        "description": (
            "Full interface analysis between two chains of a structure file. "
            "Computes BSA (total + per-residue), interface residues with type "
            "classification, H-bonds with geometry, pairwise contact map with "
            "interaction classification, gap residue flags, and pLDDT scores. "
            "Accepts .cif and .pdb files."
        ),
        "parameters": {
            "type": "object",
            "properties": {
                "file_path": {"type": "string", "description": "Absolute path to structure file (.cif or .pdb)"},
                "chain_a":   {"type": "string", "description": "Chain ID of first chain"},
                "chain_b":   {"type": "string", "description": "Chain ID of second chain"},
                "cutoff":    {"type": "number", "description": "Heavy-atom distance cutoff in Å (default 4.5)"},
            },
            "required": ["file_path", "chain_a", "chain_b"],
        },
    },
    {
        "name": "tool_get_residue_contacts",
        "description": (
            "All contacts between a single residue and a partner chain within the cutoff. "
            "Returns per-contact distances, interaction classification, H-bond details, "
            "and gap flag."
        ),
        "parameters": {
            "type": "object",
            "properties": {
                "file_path":     {"type": "string", "description": "Absolute path to structure file"},
                "chain":         {"type": "string", "description": "Chain ID containing the residue"},
                "resnum":        {"type": "integer", "description": "Residue number (auth_seq_id)"},
                "partner_chain": {"type": "string", "description": "Chain ID to check contacts against"},
                "cutoff":        {"type": "number", "description": "Heavy-atom distance cutoff in Å (default 4.5)"},
            },
            "required": ["file_path", "chain", "resnum", "partner_chain"],
        },
    },
    {
        "name": "tool_check_mutation_clash",
        "description": (
            "Estimates whether a point mutation would clash with the partner chain. "
            "Uses a Cβ heuristic. Returns clash severity: none / minor / major. "
            "Accepts 1-letter or 3-letter amino acid codes."
        ),
        "parameters": {
            "type": "object",
            "properties": {
                "file_path":     {"type": "string", "description": "Absolute path to structure file"},
                "chain":         {"type": "string", "description": "Chain ID of the residue to mutate"},
                "resnum":        {"type": "integer", "description": "Residue number (auth_seq_id)"},
                "new_aa":        {"type": "string", "description": "Proposed amino acid (1-letter or 3-letter)"},
                "partner_chain": {"type": "string", "description": "Chain ID to check clashes against"},
            },
            "required": ["file_path", "chain", "resnum", "new_aa", "partner_chain"],
        },
    },
    {
        "name": "tool_get_sequence_map",
        "description": (
            "Returns the amino acid sequence of a chain with numbering maps for AF3 JSON. "
            "Provides: 1-letter sequence string, auth_seq_id → string index map, "
            "and auth_seq_id → label_seq_id map."
        ),
        "parameters": {
            "type": "object",
            "properties": {
                "file_path": {"type": "string", "description": "Absolute path to structure file"},
                "chain":     {"type": "string", "description": "Chain ID"},
            },
            "required": ["file_path", "chain"],
        },
    },
    {
        "name": "tool_score_surface_patch",
        "description": (
            "Characterises a set of residues as a potential binding surface. "
            "Computes spatial spread (Cα RMSD), mean KD hydrophobicity, residue "
            "type breakdown, hydrophobic fraction, and a suitability rating "
            "(Excellent / Good / Marginal / Poor)."
        ),
        "parameters": {
            "type": "object",
            "properties": {
                "file_path":    {"type": "string", "description": "Absolute path to structure file"},
                "chain":        {"type": "string", "description": "Chain ID of the target surface"},
                "residue_list": {
                    "type": "array",
                    "items": {"type": "integer"},
                    "description": "List of residue numbers (auth_seq_id) defining the patch",
                },
            },
            "required": ["file_path", "chain", "residue_list"],
        },
    },
    {
        "name": "write_file",
        "description": (
            "Write text content to a file on disk. Use this to create BoltzGen YAMLs, "
            "RFD3 JSONs, SLURM submission scripts, and any other output files. "
            "Parent directories are created automatically. Returns the absolute path "
            "written so you can confirm the file was created."
        ),
        "parameters": {
            "type": "object",
            "properties": {
                "path": {
                    "type": "string",
                    "description": (
                        "Destination file path. Use the output directory supplied in "
                        "the task description. Relative paths are resolved against the "
                        "project root."
                    ),
                },
                "content": {
                    "type": "string",
                    "description": "Full text content to write to the file.",
                },
            },
            "required": ["path", "content"],
        },
    },
]


# Only design/optimizer skills should write files — analysis skills produce
# their output as return text which PipelineRunner writes to disk.
# Restricting at the schema level is more reliable than prompt instructions alone.
_WRITE_FILE_SKILLS = {"protein-design-script", "binder-optimizer"}

# Skills that need the full residue index maps for AF3/BoltzGen JSON construction
_NEEDS_INDEX_MAPS = {"protein-design-script", "binder-optimizer", "complex-structure-analysis"}

# Skills that have access to the corpus-wide PDB lookup tool
_PDB_LOOKUP_SKILLS = {"pathway-expert", "complex-expert", "orchestrator"}

_RCSB_SEARCH_URL = "https://search.rcsb.org/rcsbsearch/v2/query"
_RCSB_GRAPHQL_URL = "https://data.rcsb.org/graphql"
_RCSB_GRAPHQL_QUERY = """
query EntriesMetadata($ids: [String!]!) {
  entries(entry_ids: $ids) {
    rcsb_id
    struct { title }
    rcsb_entry_info {
      resolution_combined
      experimental_method
      polymer_entity_count_protein
    }
    polymer_entities {
      rcsb_polymer_entity { pdbx_description }
      rcsb_entity_source_organism { ncbi_taxonomy_id ncbi_scientific_name }
    }
  }
}
"""


def _parse_rcsb_entry(entry: dict) -> dict:
    """Distil an RCSB GraphQL entry to selection-relevant fields."""
    info = entry.get("rcsb_entry_info") or {}
    res_list = [r for r in (info.get("resolution_combined") or []) if r is not None]
    return {
        "title": (entry.get("struct") or {}).get("title"),
        "method": info.get("experimental_method"),
        "resolution_A": round(min(res_list), 2) if res_list else None,
        "protein_chain_count": info.get("polymer_entity_count_protein") or 0,
        "entities": [
            {
                "description": (pe.get("rcsb_polymer_entity") or {}).get("pdbx_description") or "",
                "organism_taxid": ((pe.get("rcsb_entity_source_organism") or [{}])[0]).get("ncbi_taxonomy_id"),
                "organism_name": ((pe.get("rcsb_entity_source_organism") or [{}])[0]).get("ncbi_scientific_name"),
            }
            for pe in (entry.get("polymer_entities") or [])
        ],
    }


def _search_rcsb_pdb(proteins: list[str], fingerprint_dir: Path) -> dict:
    """
    Search RCSB PDB for structures containing the given proteins.

    Uses RCSB full-text search (one request per protein, top 5 results each),
    then batch-fetches title/method/resolution/chain metadata via GraphQL for
    any IDs not already in the local pdb_metadata.json cache.

    Call this as a fallback when find_pdb_structures returns total_found=0.
    Results are from RCSB, not the corpus — verify entity descriptions match
    your target complex before using a PDB ID.
    """
    metadata_cache: dict[str, dict] = {}
    metadata_path = fingerprint_dir.parent / "pdb_metadata.json"
    if metadata_path.exists():
        try:
            metadata_cache = json.loads(metadata_path.read_text(encoding="utf-8"))
        except Exception:
            pass

    queries = [p.strip() for p in proteins if p.strip()]
    by_protein: dict[str, list[str]] = {}

    for protein in queries:
        # Search across title, keywords, and entity description for broad coverage
        payload = {
            "query": {
                "type": "group",
                "logical_operator": "or",
                "nodes": [
                    {"type": "terminal", "service": "text", "parameters": {
                        "attribute": "struct.title", "operator": "contains_words", "value": protein}},
                    {"type": "terminal", "service": "text", "parameters": {
                        "attribute": "struct_keywords.text", "operator": "contains_words", "value": protein}},
                    {"type": "terminal", "service": "text", "parameters": {
                        "attribute": "rcsb_polymer_entity.pdbx_description", "operator": "contains_words", "value": protein}},
                ],
            },
            "return_type": "entry",
            "request_options": {"paginate": {"start": 0, "rows": 5}},
        }
        try:
            resp = requests.post(_RCSB_SEARCH_URL, json=payload, timeout=15)
            resp.raise_for_status()
            ids = [hit["identifier"] for hit in resp.json().get("result_set", [])]
            by_protein[protein] = ids
        except Exception as e:
            logger.warning(f"[search_rcsb_pdb] {protein}: {e}")
            by_protein[protein] = []

    # Batch-fetch metadata for IDs not already in local cache
    new_ids = list(dict.fromkeys(
        pid for ids in by_protein.values() for pid in ids
        if pid not in metadata_cache
    ))
    if new_ids:
        try:
            resp = requests.post(
                _RCSB_GRAPHQL_URL,
                json={"query": _RCSB_GRAPHQL_QUERY, "variables": {"ids": new_ids}},
                timeout=30,
            )
            resp.raise_for_status()
            for entry in (resp.json().get("data") or {}).get("entries") or []:
                metadata_cache[entry["rcsb_id"]] = _parse_rcsb_entry(entry)
        except Exception as e:
            logger.warning(f"[search_rcsb_pdb] GraphQL batch fetch failed: {e}")

    def _enrich(pdb_id: str) -> dict:
        result: dict = {"pdb_id": pdb_id}
        result.update(metadata_cache.get(pdb_id, {}))
        return result

    return {
        "by_protein": {p: [_enrich(pid) for pid in ids] for p, ids in by_protein.items()},
        "total_found": sum(len(ids) for ids in by_protein.values()),
        "note": (
            "Results from RCSB full-text search — not corpus-sourced. "
            "Check entity descriptions to confirm your target proteins are present "
            "and apply the same selection criteria as for corpus results."
        ),
    }


def _filter_tools(defs: list[dict], skill_name: str) -> list[dict]:
    """Return the tool list for a given skill, removing tools the skill shouldn't have."""
    if skill_name not in _WRITE_FILE_SKILLS:
        defs = [d for d in defs if d["name"] != "write_file"]
    if skill_name not in _PDB_LOOKUP_SKILLS:
        defs = [d for d in defs if d["name"] != "find_pdb_structures"]
        defs = [d for d in defs if d["name"] != "search_rcsb_pdb"]
    return defs


def _find_pdb_structures(proteins: list[str], fingerprint_dir: Path) -> dict:
    """
    Scan all corpus fingerprints for PDB accessions associated with the given proteins.

    Two sources are checked for each protein:
    - pathway_context.target_nodes[].suggested_pdb_structures  (pathway biology papers)
    - paper_metadata.pdb_accessions of papers where the protein appears in
      entities.proteins or key_findings.protein_pair

    Matching is case-insensitive substring: query "YAP1" matches stored "YAP1",
    stored "YAP/TAZ", etc. Queries shorter than 3 chars are ignored.
    """
    import re as _re

    def _matches(stored: str, query: str) -> bool:
        if len(query) < 3:
            return False
        s, q = stored.upper(), query.upper()
        return q in s or s.startswith(q)

    queries = [p.strip() for p in proteins if p.strip()]
    # {query → ordered list of PDB IDs}
    by_protein: dict[str, list[str]] = {q: [] for q in queries}

    for fp_file in fingerprint_dir.glob("*.json"):
        try:
            fp = json.loads(fp_file.read_text(encoding="utf-8"))
        except Exception:
            continue

        # Only valid 4-char PDB IDs from paper_metadata
        pdb_accessions = [
            p for p in (fp.get("paper_metadata", {}).get("pdb_accessions") or [])
            if p and len(p) == 4
        ]
        target_nodes = (fp.get("pathway_context") or {}).get("target_nodes") or []
        entity_proteins = fp.get("entities", {}).get("proteins") or []
        key_findings = fp.get("key_findings") or []

        for query in queries:
            hits: set[str] = set()

            # Source 1: pathway_context.target_nodes.suggested_pdb_structures
            for node in target_nodes:
                if _matches(node.get("protein", ""), query):
                    hits.update(
                        p for p in (node.get("suggested_pdb_structures") or []) if p
                    )

            # Source 2: pdb_accessions from papers mentioning this protein
            if pdb_accessions:
                in_entities = any(_matches(ep, query) for ep in entity_proteins)
                in_findings = any(
                    any(_matches(pp, query) for pp in (kf.get("protein_pair") or []) if pp)
                    for kf in key_findings
                )
                if in_entities or in_findings:
                    hits.update(pdb_accessions)

            # Merge deduplicating while preserving order
            seen = set(by_protein[query])
            for h in sorted(hits):
                if h not in seen:
                    by_protein[query].append(h)
                    seen.add(h)

    # Load RCSB metadata cache if available
    metadata_cache: dict[str, dict] = {}
    metadata_path = fingerprint_dir.parent / "pdb_metadata.json"
    if metadata_path.exists():
        try:
            metadata_cache = json.loads(metadata_path.read_text(encoding="utf-8"))
        except Exception:
            pass

    def _enrich(pdb_id: str) -> dict:
        meta = metadata_cache.get(pdb_id.upper(), {})
        result: dict = {"pdb_id": pdb_id}
        if meta:
            result["title"] = meta.get("title")
            result["method"] = meta.get("method")
            result["resolution_A"] = meta.get("resolution_A")
            result["protein_chain_count"] = meta.get("protein_chain_count")
            result["entities"] = [
                {
                    "description": e.get("description"),
                    "organism_taxid": e.get("organism_taxid"),
                    "organism_name": e.get("organism_name"),
                }
                for e in (meta.get("entities") or [])
            ]
        return result

    all_ids = sorted({p for ids in by_protein.values() for p in ids})
    return {
        "by_protein": {q: [_enrich(pid) for pid in ids] for q, ids in by_protein.items()},
        "all_pdb_ids": all_ids,
        "total_found": len(all_ids),
        "metadata_available": bool(metadata_cache),
    }


def _to_claude_tools(defs: list[dict]) -> list[dict]:
    tools = [
        {"name": d["name"], "description": d["description"], "input_schema": d["parameters"]}
        for d in defs
    ]
    if tools:
        tools[-1]["cache_control"] = {"type": "ephemeral"}
    return tools


def _to_gemini_tools(defs: list[dict]) -> list[dict]:
    return [
        {
            "functionDeclarations": [
                {"name": d["name"], "description": d["description"], "parameters": d["parameters"]}
                for d in defs
            ]
        }
    ]


# ---------------------------------------------------------------------------
# SkillRunner
# ---------------------------------------------------------------------------

_GEMINI_GENERATE_URL = (
    "https://generativelanguage.googleapis.com/v1beta/models/{model}:generateContent"
)


class SkillRunner:
    """
    Runs one skill against Claude or Gemini via an agentic tool-calling loop.

    Parameters
    ----------
    skill_name : str
        Directory name under ``skills/``.
    provider : str
        ``"claude"`` or ``"gemini"``.
    model_id : str
        Model identifier passed directly to the API.
    config : dict
        Parsed ``config.yaml`` — used for data paths.
    max_iter : int
        Hard cap on LLM calls per run (default 30).
    """

    def __init__(
        self,
        skill_name: str,
        provider: str,
        model_id: str,
        config: dict,
        max_iter: int = 30,
        max_input_tokens: int = 100_000,
        use_extended_thinking: bool = False,
    ) -> None:
        self.skill_name = skill_name
        self.provider = provider
        self.model_id = model_id
        self.config = config
        self.max_iter = max_iter
        self.max_input_tokens = max_input_tokens
        # Extended thinking: Claude only, ignored silently for Gemini.
        # Requires max_tokens > thinking_budget; budget_tokens=10000 + 14000 output headroom = 24000.
        self.use_extended_thinking = use_extended_thinking and provider == "claude"

        # Token usage tracking — populated during run()
        self._total_input_tokens: int = 0
        self._total_output_tokens: int = 0

        # Resolve data paths (relative → absolute from project root)
        fp_dir = config.get("paths", {}).get("fingerprint_dir", "data/fingerprints")
        self._fingerprint_dir = (
            Path(fp_dir) if Path(fp_dir).is_absolute() else _ROOT / fp_dir
        )

        vs_path = config.get("vector_store", {}).get("db_path", "data/vectors")
        self._vector_db_path = str(
            Path(vs_path) if Path(vs_path).is_absolute() else _ROOT / vs_path
        )

        self._embedding_model = config.get("vector_store", {}).get(
            "embedding_model", "NeuML/pubmedbert-base-embeddings"
        )

        self._store = None  # lazy — sentence-transformers is slow to import

        # Populated after run() completes — full conversation history for tracing.
        self._messages: list[dict] | None = None

        self.system_prompt = self._load_system_prompt()
        logger.info(
            f"SkillRunner ready: skill={skill_name}, provider={provider}, model={model_id}"
            + (" [extended thinking]" if self.use_extended_thinking else "")
        )

    # ------------------------------------------------------------------
    # System prompt loading
    # ------------------------------------------------------------------

    def _load_system_prompt(self) -> str:
        skills_root = _ROOT / "skills"
        skill_path = skills_root / self.skill_name / "SKILL.md"
        if not skill_path.exists():
            raise FileNotFoundError(f"SKILL.md not found: {skill_path}")

        system = skill_path.read_text(encoding="utf-8")

        if self.skill_name == "orchestrator":
            for sub_dir in sorted(skills_root.iterdir()):
                if sub_dir.name == "orchestrator" or not sub_dir.is_dir():
                    continue
                sub_md = sub_dir / "SKILL.md"
                if sub_md.exists():
                    system += (
                        f"\n\n---\n## SUB-SKILL: {sub_dir.name}\n"
                        + sub_md.read_text(encoding="utf-8")
                    )
            logger.info("Orchestrator mode: sub-skill SKILL.mds appended to system prompt")

        return system

    # ------------------------------------------------------------------
    # Tool execution
    # ------------------------------------------------------------------

    def _get_store(self):
        if self._store is None:
            from src.vector_store import VectorStore
            logger.info("Initialising VectorStore (lazy, first search_corpus call)…")
            self._store = VectorStore(
                db_path=self._vector_db_path,
                embedding_model=self._embedding_model,
            )
        return self._store

    def _execute_tool(self, name: str, input_dict: dict) -> str:
        try:
            if name == "search_corpus":
                raw = self._get_store().execute_search_tool(input_dict)
                # Strip the 'papers' JSON array — it duplicates the formatted result_text
                # and can add 40k+ tokens when top_k is large. The model reads result_text
                # and calls get_fingerprint for papers it wants full details on.
                try:
                    parsed = json.loads(raw)
                    parsed.pop("papers", None)
                    return json.dumps(parsed, ensure_ascii=False)
                except (json.JSONDecodeError, AttributeError):
                    return raw

            if name == "get_fingerprint":
                from src.fingerprint_store import load_fingerprint
                identifier = input_dict.get("identifier", "")
                if not identifier.startswith("doi:") and not identifier.startswith("pmcid:"):
                    paper_key = f"doi:{identifier}"
                else:
                    paper_key = identifier
                fp = load_fingerprint(paper_key, self._fingerprint_dir)
                if fp is None:
                    return json.dumps({"error": f"No fingerprint found for '{identifier}'"})
                # Strip fields never used by any skill to reduce token cost.
                # Skills that need methodology or contradictions can override this.
                fp.pop("curation_metadata", None)
                fp.pop("contradictions_and_negative_results", None)
                fp.pop("methodology", None)
                return json.dumps(fp, ensure_ascii=False, indent=2)

            if name == "find_pdb_structures":
                result = _find_pdb_structures(
                    input_dict.get("proteins", []), self._fingerprint_dir
                )
                return json.dumps(result, ensure_ascii=False, indent=2)

            if name == "search_rcsb_pdb":
                result = _search_rcsb_pdb(
                    input_dict.get("proteins", []), self._fingerprint_dir
                )
                return json.dumps(result, ensure_ascii=False, indent=2)

            if name == "tool_analyze_interface":
                from src.structure_tools import analyze_interface
                result = analyze_interface(
                    _resolve(input_dict["file_path"]),
                    input_dict["chain_a"],
                    input_dict["chain_b"],
                    float(input_dict.get("cutoff", 4.5)),
                )
                return json.dumps(result, indent=2)

            if name == "tool_get_residue_contacts":
                from src.structure_tools import get_residue_contacts
                result = get_residue_contacts(
                    _resolve(input_dict["file_path"]),
                    input_dict["chain"],
                    int(input_dict["resnum"]),
                    input_dict["partner_chain"],
                    float(input_dict.get("cutoff", 4.5)),
                )
                return json.dumps(result, indent=2)

            if name == "tool_check_mutation_clash":
                from src.structure_tools import check_mutation_clash
                aa = str(input_dict["new_aa"]).strip().upper()
                if len(aa) == 1:
                    aa = _ONE_TO_THREE.get(aa, aa)
                result = check_mutation_clash(
                    _resolve(input_dict["file_path"]),
                    input_dict["chain"],
                    int(input_dict["resnum"]),
                    aa,
                    input_dict["partner_chain"],
                )
                return json.dumps(result, indent=2)

            if name == "tool_get_sequence_map":
                from src.structure_tools import get_sequence_map
                result = get_sequence_map(_resolve(input_dict["file_path"]), input_dict["chain"])
                # auth_to_string_idx and auth_to_label_idx are large index dicts.
                # complex-structure-analysis needs auth_to_label to populate the
                # MODEL-READY HOTSPOTS table with correct label_seq_ids (not estimates).
                # Design/optimizer skills need both maps for AF3 JSON construction.
                # Strip both for all other skills (molecular-biology-expert etc.).
                if self.skill_name not in _NEEDS_INDEX_MAPS:
                    result = {"sequence": result["sequence"], "length": len(result["sequence"])}
                return json.dumps(result, indent=2)

            if name == "tool_score_surface_patch":
                from src.structure_tools import score_surface_patch
                result = score_surface_patch(
                    _resolve(input_dict["file_path"]),
                    input_dict["chain"],
                    [int(r) for r in input_dict["residue_list"]],
                )
                return json.dumps(result, indent=2)

            if name == "write_file":
                dest = Path(_resolve(input_dict["path"]))
                dest.parent.mkdir(parents=True, exist_ok=True)
                dest.write_text(input_dict["content"], encoding="utf-8")
                logger.info(f"write_file → {dest}")
                return json.dumps({"written": str(dest)})

            return json.dumps({"error": f"Unknown tool: {name}"})

        except Exception as exc:
            logger.warning(f"Tool '{name}' raised: {exc}")
            return json.dumps({"error": str(exc)})

    # ------------------------------------------------------------------
    # Main entry point
    # ------------------------------------------------------------------

    def run(
        self,
        query: str,
        context_text: str | None = None,
        trace_path: str | Path | None = None,
    ) -> str:
        """
        Run the agentic loop and return the final report text.

        Parameters
        ----------
        query : str
            User query.
        context_text : str | None
            Optional prior report to include as context (prepended to query).
        trace_path : str | Path | None
            If provided, write a conversation trace to this directory after the
            run completes.  Two files are written:
              <trace_path>/trace_raw.json      — full message history as JSON
              <trace_path>/trace_rendered.md   — human-readable markdown trace
        """
        user_content = query
        if context_text:
            user_content = (
                f"## Context from prior report\n\n{context_text}\n\n---\n\n{query}"
            )

        if self.provider == "claude":
            messages: list[dict] = [{"role": "user", "content": user_content}]
            result = self._run_claude(messages)
        else:
            messages = [{"role": "user", "parts": [{"text": user_content}]}]
            result = self._run_gemini(messages)

        if trace_path is not None:
            self.write_trace(Path(trace_path))

        return result

    # ------------------------------------------------------------------
    # Trace output
    # ------------------------------------------------------------------

    def write_trace(self, dest: Path) -> None:
        """
        Write the conversation history from the last run() to *dest*.

        Creates two files:
          dest/trace_raw.json     — raw message list (machine-readable)
          dest/trace_rendered.md  — annotated markdown (human-readable)

        Must be called after run().  Raises RuntimeError if no run has completed.
        """
        if self._messages is None:
            raise RuntimeError("No trace available — call run() first.")

        dest.mkdir(parents=True, exist_ok=True)

        # --- raw JSON ---
        raw_path = dest / "trace_raw.json"
        raw_path.write_text(
            json.dumps(self._messages, indent=2, ensure_ascii=False),
            encoding="utf-8",
        )
        logger.info(f"Trace raw JSON → {raw_path}")

        # --- rendered markdown ---
        md_path = dest / "trace_rendered.md"
        md_path.write_text(
            self._render_trace(), encoding="utf-8"
        )
        logger.info(f"Trace markdown → {md_path}")

    def _render_trace(self) -> str:
        """Render self._messages as an annotated markdown document."""
        assert self._messages is not None

        lines: list[str] = [
            f"# Conversation Trace — `{self.skill_name}`",
            f"",
            f"**Model:** `{self.model_id}`  ",
            f"**Provider:** {self.provider}  ",
            f"**Total LLM calls:** {self._count_assistant_turns()}  ",
            f"**Tokens:** {self._total_input_tokens:,} in / {self._total_output_tokens:,} out",
            f"",
            "---",
            "",
            "## System Prompt (SKILL.md)",
            "",
            self.system_prompt,
            "",
            "---",
            "",
        ]

        user_turn = 0
        assistant_turn = 0

        for msg in self._messages:
            role = msg.get("role", "")

            # ----------------------------------------------------------
            # Claude format
            # ----------------------------------------------------------
            if role == "user":
                content = msg.get("content", "")
                if isinstance(content, str):
                    # Initial query (plain string)
                    user_turn += 1
                    lines += [
                        f"## Turn {user_turn} — User Query",
                        "",
                        content,
                        "",
                        "---",
                        "",
                    ]
                elif isinstance(content, list):
                    # Tool results turn
                    user_turn += 1
                    lines += [f"## Turn {user_turn} — Tool Results", ""]
                    for block in content:
                        if block.get("type") == "tool_result":
                            result_text = block.get("content", "")
                            # Pretty-print JSON results; fall back to raw text
                            try:
                                parsed = json.loads(result_text)
                                formatted = json.dumps(parsed, indent=2, ensure_ascii=False)
                            except (json.JSONDecodeError, TypeError):
                                formatted = result_text
                            # Truncate very large results for readability
                            if len(formatted) > 3000:
                                formatted = formatted[:3000] + "\n… [truncated]"
                            lines += [
                                f"**Tool use ID:** `{block.get('tool_use_id', '')}`",
                                "",
                                "```json",
                                formatted,
                                "```",
                                "",
                            ]
                    lines += ["---", ""]

            elif role == "assistant":
                assistant_turn += 1
                content = msg.get("content", [])
                lines += [f"## Turn {assistant_turn} — Assistant", ""]

                for block in content:
                    btype = block.get("type", "")

                    if btype == "thinking":
                        thinking_text = block.get("thinking", "")
                        lines += [
                            "### Thinking",
                            "",
                            "> " + thinking_text.replace("\n", "\n> "),
                            "",
                        ]

                    elif btype == "text":
                        lines += [
                            "### Response Text",
                            "",
                            block.get("text", ""),
                            "",
                        ]

                    elif btype == "tool_use":
                        tool_inputs = json.dumps(
                            block.get("input", {}), indent=2, ensure_ascii=False
                        )
                        lines += [
                            f"### Tool Call — `{block.get('name', '')}`",
                            "",
                            f"**ID:** `{block.get('id', '')}`",
                            "",
                            "```json",
                            tool_inputs,
                            "```",
                            "",
                        ]

                lines += ["---", ""]

            # ----------------------------------------------------------
            # Gemini format (parts-based)
            # ----------------------------------------------------------
            elif role == "model":
                assistant_turn += 1
                lines += [f"## Turn {assistant_turn} — Assistant (Gemini)", ""]
                for part in msg.get("parts", []):
                    if "text" in part:
                        lines += ["### Response Text", "", part["text"], ""]
                    elif "functionCall" in part:
                        fc = part["functionCall"]
                        lines += [
                            f"### Tool Call — `{fc.get('name', '')}`",
                            "",
                            "```json",
                            json.dumps(fc.get("args", {}), indent=2, ensure_ascii=False),
                            "```",
                            "",
                        ]
                lines += ["---", ""]

            elif role == "user" and msg.get("parts"):
                # Gemini tool result turn
                user_turn += 1
                lines += [f"## Turn {user_turn} — Tool Results (Gemini)", ""]
                for part in msg.get("parts", []):
                    if "functionResponse" in part:
                        fr = part["functionResponse"]
                        result_str = json.dumps(
                            fr.get("response", {}).get("result", ""),
                            indent=2, ensure_ascii=False,
                        )
                        if len(result_str) > 3000:
                            result_str = result_str[:3000] + "\n… [truncated]"
                        lines += [
                            f"**Function:** `{fr.get('name', '')}`",
                            "",
                            "```json",
                            result_str,
                            "```",
                            "",
                        ]
                lines += ["---", ""]

        return "\n".join(lines)

    def _count_assistant_turns(self) -> int:
        if not self._messages:
            return 0
        return sum(
            1 for m in self._messages
            if m.get("role") in ("assistant", "model")
        )

    # ------------------------------------------------------------------
    # Claude agentic loop
    # ------------------------------------------------------------------

    def _run_claude(self, messages: list[dict]) -> str:
        client = anthropic.Anthropic()
        claude_tools = _to_claude_tools(_filter_tools(_TOOL_DEFS, self.skill_name))

        for iteration in range(self.max_iter):
            logger.info(f"[claude] call #{iteration + 1} — messages={len(messages)}")

            # Extended thinking: budget_tokens must be < max_tokens.
            # We allocate 10 000 to thinking and leave 14 000 for visible output.
            thinking_param = (
                {"thinking": {"type": "enabled", "budget_tokens": 10000}}
                if self.use_extended_thinking
                else {}
            )

            # Retry up to 3 times on rate-limit and transient connection errors.
            # Use streaming — required by the SDK when max_tokens is large enough
            # that the request could exceed 10 minutes non-streamed.
            for attempt in range(3):
                try:
                    with client.messages.stream(
                        model=self.model_id,
                        max_tokens=24000,
                        system=[{"type": "text", "text": self.system_prompt, "cache_control": {"type": "ephemeral"}}],
                        tools=claude_tools,
                        messages=messages,
                        **thinking_param,
                    ) as stream:
                        response = stream.get_final_message()
                    break
                except anthropic.RateLimitError:
                    if attempt == 2:
                        raise
                    wait = 65 * (attempt + 1)
                    logger.warning(f"Rate limit hit — waiting {wait}s then retrying…")
                    time.sleep(wait)
                except anthropic.APIConnectionError:
                    if attempt == 2:
                        raise
                    wait = 10 * (attempt + 1)
                    logger.warning(f"Connection error on call #{iteration + 1} (attempt {attempt + 1}/3) — retrying in {wait}s")
                    time.sleep(wait)
                except anthropic.AnthropicError as exc:
                    # Catch overloaded_error (529) and retry with backoff.
                    if attempt == 2 or "overloaded" not in str(exc).lower():
                        raise
                    wait = 30 * (attempt + 1)
                    logger.warning(f"API overloaded on call #{iteration + 1} (attempt {attempt + 1}/3) — retrying in {wait}s")
                    time.sleep(wait)

            # Serialise content blocks for history.
            # thinking blocks: must round-trip in message history but are never
            # included in the visible text output — they are the model's scratchpad.
            content_list: list[dict] = []
            text_parts: list[str] = []
            tool_use_blocks = []

            for block in response.content:
                if block.type == "thinking":
                    # Preserve in history; never emit to output text.
                    content_list.append({"type": "thinking", "thinking": block.thinking})
                elif block.type == "text":
                    text_parts.append(block.text)
                    content_list.append({"type": "text", "text": block.text})
                elif block.type == "tool_use":
                    tool_use_blocks.append(block)
                    content_list.append({
                        "type": "tool_use",
                        "id": block.id,
                        "name": block.name,
                        "input": block.input,
                    })

            in_tok = response.usage.input_tokens
            out_tok = response.usage.output_tokens
            cache_created = getattr(response.usage, "cache_creation_input_tokens", 0) or 0
            cache_read = getattr(response.usage, "cache_read_input_tokens", 0) or 0
            self._total_input_tokens += in_tok
            self._total_output_tokens += out_tok
            cache_info = f" | cache_created={cache_created:,} / cache_read={cache_read:,}" if (cache_created or cache_read) else ""
            logger.info(
                f"  tokens: {in_tok:,} in / {out_tok:,} out{cache_info} "
                f"(run cumulative: {self._total_input_tokens:,} in / "
                f"{self._total_output_tokens:,} out)"
            )

            if response.stop_reason == "max_tokens":
                logger.warning(
                    f"Response truncated at max_tokens on call #{iteration + 1} "
                    f"({out_tok:,} out) — '### PIPELINE HANDOFF' may be missing."
                )

            if in_tok > self.max_input_tokens:
                raise RuntimeError(
                    f"Input token limit exceeded on call #{iteration + 1}: "
                    f"{in_tok:,} tokens in one request "
                    f"(limit: {self.max_input_tokens:,}). "
                    f"Run total so far: {self._total_input_tokens:,} in / "
                    f"{self._total_output_tokens:,} out. "
                    f"Reduce top_k, use a shorter query, or raise --max-tokens."
                )

            messages.append({"role": "assistant", "content": content_list})

            if not tool_use_blocks:
                logger.info(
                    f"Run complete — total tokens: {self._total_input_tokens:,} in / "
                    f"{self._total_output_tokens:,} out across {iteration + 1} LLM calls"
                )
                self._messages = messages
                return "\n".join(text_parts)

            # Execute all tool calls and batch results
            tool_results: list[dict] = []
            for block in tool_use_blocks:
                logger.info(f"  → {block.name}({list(block.input.keys())})")
                result = self._execute_tool(block.name, block.input)
                tool_results.append({
                    "type": "tool_result",
                    "tool_use_id": block.id,
                    "content": result,
                })

            messages.append({"role": "user", "content": tool_results})

        raise RuntimeError(
            f"Max iterations ({self.max_iter}) exceeded for skill '{self.skill_name}'"
        )

    # ------------------------------------------------------------------
    # Gemini agentic loop
    # ------------------------------------------------------------------

    def _run_gemini(self, messages: list[dict]) -> str:
        api_key = os.environ.get("GEMINI_API_KEY", "")
        url = _GEMINI_GENERATE_URL.format(model=self.model_id)
        gemini_tools = _to_gemini_tools(_filter_tools(_TOOL_DEFS, self.skill_name))

        for iteration in range(self.max_iter):
            logger.info(f"[gemini] call #{iteration + 1} — messages={len(messages)}")

            payload = {
                "system_instruction": {"parts": [{"text": self.system_prompt}]},
                "contents": messages,
                "tools": gemini_tools,
                "generationConfig": {"maxOutputTokens": 24000},
            }
            for attempt in range(4):
                resp = requests.post(
                    url, params={"key": api_key}, json=payload, timeout=180
                )
                if resp.status_code not in (429, 500, 502, 503, 504) or attempt == 3:
                    break
                if resp.status_code == 429:
                    # Honour Retry-After if present; otherwise use exponential backoff
                    retry_after = resp.headers.get("Retry-After") or resp.headers.get("retry-after")
                    wait = int(retry_after) if retry_after and retry_after.isdigit() else 30 * (attempt + 1)
                else:
                    wait = 10 * (attempt + 1)
                logger.warning(
                    f"[gemini] transient {resp.status_code} on call #{iteration + 1} "
                    f"(attempt {attempt + 1}/4) — retrying in {wait}s"
                )
                time.sleep(wait)
            resp.raise_for_status()
            body = resp.json()

            candidate = body["candidates"][0]
            parts: list[dict] = candidate["content"]["parts"]

            if candidate.get("finishReason") == "MAX_TOKENS":
                logger.warning(
                    f"Gemini response truncated at maxOutputTokens on call #{iteration + 1} "
                    f"— '### PIPELINE HANDOFF' may be missing."
                )

            usage = body.get("usageMetadata", {})
            in_tok = usage.get("promptTokenCount", 0)
            out_tok = usage.get("candidatesTokenCount", 0)
            self._total_input_tokens += in_tok
            self._total_output_tokens += out_tok
            logger.info(
                f"  tokens: {in_tok:,} in / {out_tok:,} out "
                f"(run cumulative: {self._total_input_tokens:,} in / "
                f"{self._total_output_tokens:,} out)"
            )

            if in_tok > self.max_input_tokens:
                raise RuntimeError(
                    f"Input token limit exceeded on call #{iteration + 1}: "
                    f"{in_tok:,} tokens in one request "
                    f"(limit: {self.max_input_tokens:,}). "
                    f"Run total so far: {self._total_input_tokens:,} in / "
                    f"{self._total_output_tokens:,} out. "
                    f"Reduce top_k, use a shorter query, or raise --max-tokens."
                )

            # Append model turn to history
            messages.append({"role": "model", "parts": parts})

            function_calls = [p["functionCall"] for p in parts if "functionCall" in p]

            if not function_calls:
                logger.info(
                    f"Run complete — total tokens: {self._total_input_tokens:,} in / "
                    f"{self._total_output_tokens:,} out across {iteration + 1} LLM calls"
                )
                self._messages = messages
                text_parts = [p.get("text", "") for p in parts if "text" in p]
                return "\n".join(text_parts)

            # Execute tools; batch all functionResponses in one user turn
            function_responses: list[dict] = []
            for fc in function_calls:
                name = fc["name"]
                args = fc.get("args", {})
                logger.info(f"  → {name}({list(args.keys())})")
                result = self._execute_tool(name, args)
                function_responses.append({
                    "functionResponse": {
                        "name": name,
                        "response": {"result": result},
                    }
                })

            messages.append({"role": "user", "parts": function_responses})

        raise RuntimeError(
            f"Max iterations ({self.max_iter}) exceeded for skill '{self.skill_name}'"
        )
